import { Component, OnInit, Inject, ViewChild } from '@angular/core';
import html2canvas from 'html2canvas';
import { Observable } from 'rxjs';
import { MatSelect } from '@angular/material/select';
import { MatOption } from '@angular/material/core';
import {
  FormBuilder,
  FormControlName,
  FormGroup,
  Validators,
} from '@angular/forms';

import * as JSZip from 'jszip';
let zipFile: JSZip = new JSZip();
import * as FileSaver from 'file-saver';
import * as saveAs from 'file-saver';

@Component({
  templateUrl: './cards.component.html',
  styleUrls: ['./cards.component.css'],
})
export class CardsComponent implements OnInit {
  selectedFiles?: FileList;
  selectedFileNames: string[] = [];
  progressInfos: any[] = [];
  message: string[] = [];
  previews: string[] = [];

  userLists: any[] = [
    {
      address: 'Bharatpur, Chitwan',
      address2: 'Bharatpur-10, Dipendra Nagar',
      altaddress_address: 'Kirtipur',
      altaddress_address2: '',
      altaddress_city: 'Kathmandu',
      altaddress_country: '',
      altaddress_email: '',
      altaddress_notes: '',
      altaddress_phone: '',
      altaddress_postal_code: '',
      altaddress_state: '',
      altaddress_street_number: '',
      altaddress_street_type: null,
      altcontact_address: '',
      altcontact_address2: '',
      altcontact_city: '',
      altcontact_country: '',
      altcontact_firstname: '',
      altcontact_phone: '',
      altcontact_postal_code: '',
      altcontact_state: '',
      altcontact_surname: '',
      anonymized: false,
      autorenew_checkouts: false,
      cardnumber: '00003',
      category_id: 'TCLSG1',
      check_previous_checkout: 'inherit',
      city: 'Chitwan',
      country: '',
      date_enrolled: '2010-11-10',
      date_of_birth: '1962-10-09',
      date_renewed: null,
      email: 'indiraghimire@hotmail.com',
      expiry_date: '2025-11-10',
      fax: '',
      firstname: 'Indira',
      gender: 'F',
      incorrect_address: false,
      initials: '',
      lang: 'default',
      last_seen: null,
      library_id: 'TUCL',
      login_attempts: 0,
      mobile: '9841897958/ 014330189',
      opac_notes: 'please change your OPAC password',
      other_name: '',
      overdrive_auth_token: null,
      patron_card_lost: false,
      patron_id: 61,
      phone: '2150120',
      postal_code: '',
      privacy: 1,
      privacy_guarantor_checkouts: 0,
      privacy_guarantor_fines: false,
      relationship_type: null,
      restricted: false,
      secondary_email: '',
      secondary_phone: '',
      sms_number: null,
      sms_provider_id: null,
      staff_notes: '',
      state: '',
      statistics_1: '',
      statistics_2: '',
      street_number: '',
      street_type: null,
      surname: 'Ghimire (Koirala)',
      title: 'Mrs',
      updated_on: '2021-12-09T10:43:40+05:45',
      userid: 'indirakoirala.ghimire',
    },
    {
      address: 'Dhapasi, Kathmandu',
      address2: '',
      altaddress_address: '',
      altaddress_address2: null,
      altaddress_city: '',
      altaddress_country: null,
      altaddress_email: '',
      altaddress_notes: '',
      altaddress_phone: '',
      altaddress_postal_code: '',
      altaddress_state: null,
      altaddress_street_number: null,
      altaddress_street_type: null,
      altcontact_address: '',
      altcontact_address2: '',
      altcontact_city: '',
      altcontact_country: null,
      altcontact_firstname: '',
      altcontact_phone: '',
      altcontact_postal_code: '',
      altcontact_state: null,
      altcontact_surname: '',
      anonymized: false,
      autorenew_checkouts: false,
      cardnumber: '00005',
      category_id: 'TCLSG1',
      check_previous_checkout: 'inherit',
      city: 'Kathmandu',
      country: null,
      date_enrolled: '2010-10-20',
      date_of_birth: '1956-07-03',
      date_renewed: null,
      email: 'radhabhattarai82@hotmail.com',
      expiry_date: '2011-10-20',
      fax: '',
      firstname: "Radha 'Newa'",
      gender: 'F',
      incorrect_address: false,
      initials: '',
      lang: 'default',
      last_seen: null,
      library_id: 'TUCL',
      login_attempts: 0,
      mobile: '',
      opac_notes: '',
      other_name: '',
      overdrive_auth_token: null,
      patron_card_lost: false,
      patron_id: 63,
      phone: '4355627',
      postal_code: '',
      privacy: 1,
      privacy_guarantor_checkouts: 0,
      privacy_guarantor_fines: false,
      relationship_type: null,
      restricted: false,
      secondary_email: 'radhanewa.bhattarai@tucl.org.np',
      secondary_phone: '',
      sms_number: null,
      sms_provider_id: null,
      staff_notes: '',
      state: null,
      statistics_1: '',
      statistics_2: '',
      street_number: '',
      street_type: null,
      surname: 'Bhattarai',
      title: 'Mrs',
      updated_on: '2021-12-09T10:43:40+05:45',
      userid: 'radhanewa.bhattarai',
    },
    {
      address: 'Baneshwor, Kathmandu',
      address2: '',
      altaddress_address: '',
      altaddress_address2: '',
      altaddress_city: '',
      altaddress_country: '',
      altaddress_email: '',
      altaddress_notes: '',
      altaddress_phone: '',
      altaddress_postal_code: '',
      altaddress_state: '',
      altaddress_street_number: null,
      altaddress_street_type: null,
      altcontact_address: '',
      altcontact_address2: '',
      altcontact_city: '',
      altcontact_country: '',
      altcontact_firstname: '',
      altcontact_phone: '',
      altcontact_postal_code: '',
      altcontact_state: '',
      altcontact_surname: '',
      anonymized: false,
      autorenew_checkouts: false,
      cardnumber: '00008',
      category_id: 'TCLSG1',
      check_previous_checkout: 'inherit',
      city: '',
      country: '',
      date_enrolled: '2010-11-28',
      date_of_birth: '1972-02-27',
      date_renewed: null,
      email: 'sabitribaral@gmail.com',
      expiry_date: '2015-11-27',
      fax: '',
      firstname: 'Sabitri',
      gender: 'F',
      incorrect_address: false,
      initials: '',
      lang: 'default',
      last_seen: null,
      library_id: 'TUCL',
      login_attempts: 0,
      mobile: '',
      opac_notes: 'Please change your OPAC password',
      other_name: '',
      overdrive_auth_token: null,
      patron_card_lost: false,
      patron_id: 65,
      phone: '4490814',
      postal_code: '',
      privacy: 1,
      privacy_guarantor_checkouts: 0,
      privacy_guarantor_fines: false,
      relationship_type: null,
      restricted: false,
      secondary_email: 'sabitri.baral@tucl.org.np',
      secondary_phone: '9860582951',
      sms_number: null,
      sms_provider_id: null,
      staff_notes: '',
      state: '',
      statistics_1: '',
      statistics_2: '',
      street_number: '',
      street_type: null,
      surname: 'Baral',
      title: 'Mrs',
      updated_on: '2021-12-09T10:43:40+05:45',
      userid: 'sabitri.baral',
    },
    {
      address: 'Sanepa, Lalitpur-2',
      address2: 'Lalitpur-2',
      altaddress_address: '',
      altaddress_address2: null,
      altaddress_city: '',
      altaddress_country: null,
      altaddress_email: '',
      altaddress_notes: '',
      altaddress_phone: '',
      altaddress_postal_code: '',
      altaddress_state: null,
      altaddress_street_number: null,
      altaddress_street_type: null,
      altcontact_address: '',
      altcontact_address2: '',
      altcontact_city: '',
      altcontact_country: null,
      altcontact_firstname: '',
      altcontact_phone: '',
      altcontact_postal_code: '',
      altcontact_state: null,
      altcontact_surname: '',
      anonymized: false,
      autorenew_checkouts: false,
      cardnumber: '00014',
      category_id: 'TCLSG1',
      check_previous_checkout: 'inherit',
      city: '',
      country: '',
      date_enrolled: '2010-11-28',
      date_of_birth: '2031-08-15',
      date_renewed: null,
      email: 'adbasnet@yahoo.com',
      expiry_date: '2015-11-27',
      fax: '',
      firstname: 'Aradhana ',
      gender: 'F',
      incorrect_address: false,
      initials: '',
      lang: 'default',
      last_seen: null,
      library_id: 'TUCL',
      login_attempts: 0,
      mobile: '',
      opac_notes: 'Please change your OPAC password',
      other_name: '',
      overdrive_auth_token: null,
      patron_card_lost: false,
      patron_id: 67,
      phone: '9851049408',
      postal_code: '',
      privacy: 1,
      privacy_guarantor_checkouts: 0,
      privacy_guarantor_fines: false,
      relationship_type: null,
      restricted: false,
      secondary_email: 'aradhana.basnet@tucl.org.np',
      secondary_phone: '',
      sms_number: null,
      sms_provider_id: null,
      staff_notes: '',
      state: '',
      statistics_1: '',
      statistics_2: '',
      street_number: '',
      street_type: null,
      surname: 'Basnet',
      title: 'Mrs',
      updated_on: '2021-12-09T10:43:40+05:45',
      userid: 'aradhana.basnet',
    },
    {
      address: 'Jorpati,2  Kathmandu',
      address2: '',
      altaddress_address: '',
      altaddress_address2: '',
      altaddress_city: '',
      altaddress_country: '',
      altaddress_email: '',
      altaddress_notes: '',
      altaddress_phone: '',
      altaddress_postal_code: '',
      altaddress_state: '',
      altaddress_street_number: null,
      altaddress_street_type: null,
      altcontact_address: '',
      altcontact_address2: '',
      altcontact_city: '',
      altcontact_country: '',
      altcontact_firstname: '',
      altcontact_phone: '',
      altcontact_postal_code: '',
      altcontact_state: '',
      altcontact_surname: '',
      anonymized: false,
      autorenew_checkouts: false,
      cardnumber: '00011',
      category_id: 'TCLSG1',
      check_previous_checkout: 'inherit',
      city: 'Kathmandu',
      country: '',
      date_enrolled: '2010-11-28',
      date_of_birth: '1973-11-25',
      date_renewed: null,
      email: '',
      expiry_date: '2020-11-27',
      fax: '',
      firstname: 'Sagar Raj',
      gender: 'M',
      incorrect_address: false,
      initials: '',
      lang: 'default',
      last_seen: null,
      library_id: 'TUCL',
      login_attempts: 0,
      mobile: '',
      opac_notes: 'Please change your OPAC Password',
      other_name: '',
      overdrive_auth_token: null,
      patron_card_lost: false,
      patron_id: 68,
      phone: '9841364473',
      postal_code: '',
      privacy: 1,
      privacy_guarantor_checkouts: 0,
      privacy_guarantor_fines: false,
      relationship_type: null,
      restricted: false,
      secondary_email: 'subedisagarraj@gmail.com',
      secondary_phone: '4485529',
      sms_number: null,
      sms_provider_id: null,
      staff_notes: '',
      state: '',
      statistics_1: '',
      statistics_2: '',
      street_number: '',
      street_type: null,
      surname: 'Subedi',
      title: 'Mr',
      updated_on: '2021-12-09T10:43:40+05:45',
      userid: 'sagarraj.subedi',
    },
    {
      address: 'Kirtipur-17, Kathmandu',
      address2: '',
      altaddress_address: '',
      altaddress_address2: '',
      altaddress_city: '',
      altaddress_country: '',
      altaddress_email: '',
      altaddress_notes: '',
      altaddress_phone: '',
      altaddress_postal_code: '',
      altaddress_state: '',
      altaddress_street_number: null,
      altaddress_street_type: null,
      altcontact_address: '',
      altcontact_address2: '',
      altcontact_city: '',
      altcontact_country: '',
      altcontact_firstname: '',
      altcontact_phone: '',
      altcontact_postal_code: '',
      altcontact_state: '',
      altcontact_surname: '',
      anonymized: false,
      autorenew_checkouts: false,
      cardnumber: '00018',
      category_id: 'TCLSG2',
      check_previous_checkout: 'inherit',
      city: '',
      country: '',
      date_enrolled: '2010-11-28',
      date_of_birth: '2022-09-15',
      date_renewed: null,
      email: 'rsm_suman@yahoo.com',
      expiry_date: '2020-09-16',
      fax: '',
      firstname: 'Ramsharan',
      gender: 'M',
      incorrect_address: false,
      initials: '',
      lang: 'default',
      last_seen: null,
      library_id: 'TUCL',
      login_attempts: 0,
      mobile: '',
      opac_notes: 'Please change your OPAC password',
      other_name: '',
      overdrive_auth_token: null,
      patron_card_lost: false,
      patron_id: 69,
      phone: '9843520807',
      postal_code: '',
      privacy: 1,
      privacy_guarantor_checkouts: 0,
      privacy_guarantor_fines: false,
      relationship_type: null,
      restricted: false,
      secondary_email: 'ramsharan.maharjan@tucl.org.np',
      secondary_phone: '',
      sms_number: null,
      sms_provider_id: null,
      staff_notes: '',
      state: '',
      statistics_1: '',
      statistics_2: '',
      street_number: '',
      street_type: null,
      surname: 'Maharjan',
      title: 'Mr',
      updated_on: '2021-12-09T10:43:40+05:45',
      userid: 'ramsharan.maharjan',
    },
    {
      address: 'Kirtipur Municipality-16,Kathmandu',
      address2: '',
      altaddress_address: '',
      altaddress_address2: '',
      altaddress_city: '',
      altaddress_country: '',
      altaddress_email: '',
      altaddress_notes: '',
      altaddress_phone: '',
      altaddress_postal_code: '',
      altaddress_state: '',
      altaddress_street_number: null,
      altaddress_street_type: null,
      altcontact_address: '',
      altcontact_address2: '',
      altcontact_city: '',
      altcontact_country: '',
      altcontact_firstname: '',
      altcontact_phone: '',
      altcontact_postal_code: '',
      altcontact_state: '',
      altcontact_surname: '',
      anonymized: false,
      autorenew_checkouts: false,
      cardnumber: '00013',
      category_id: 'TCLSG1',
      check_previous_checkout: 'inherit',
      city: '',
      country: '',
      date_enrolled: '2010-10-20',
      date_of_birth: '2026-06-10',
      date_renewed: null,
      email: 'rabindra.maharjan@tucl.org.np',
      expiry_date: '2022-12-31',
      fax: '',
      firstname: ' Rabindra',
      gender: 'M',
      incorrect_address: false,
      initials: '',
      lang: 'default',
      last_seen: null,
      library_id: 'TUCL',
      login_attempts: 0,
      mobile: '',
      opac_notes: 'Please change your OPAC Password',
      other_name: '',
      overdrive_auth_token: null,
      patron_card_lost: false,
      patron_id: 70,
      phone: '4334487',
      postal_code: '',
      privacy: 1,
      privacy_guarantor_checkouts: 0,
      privacy_guarantor_fines: false,
      relationship_type: null,
      restricted: false,
      secondary_email: '',
      secondary_phone: '',
      sms_number: null,
      sms_provider_id: null,
      staff_notes: '',
      state: '',
      statistics_1: '',
      statistics_2: '',
      street_number: '',
      street_type: null,
      surname: 'Maharjan',
      title: 'Mr',
      updated_on: '2021-12-09T10:43:40+05:45',
      userid: 'rabindra.maharjan',
    },
    {
      address: 'Gupteshwor, Bhojpur',
      address2: '',
      altaddress_address: '',
      altaddress_address2: '',
      altaddress_city: '',
      altaddress_country: '',
      altaddress_email: '',
      altaddress_notes: '',
      altaddress_phone: '',
      altaddress_postal_code: '',
      altaddress_state: '',
      altaddress_street_number: null,
      altaddress_street_type: null,
      altcontact_address: '',
      altcontact_address2: '',
      altcontact_city: '',
      altcontact_country: '',
      altcontact_firstname: '',
      altcontact_phone: '',
      altcontact_postal_code: '',
      altcontact_state: '',
      altcontact_surname: '',
      anonymized: false,
      autorenew_checkouts: false,
      cardnumber: '00017',
      category_id: 'TCLSG1',
      check_previous_checkout: 'inherit',
      city: '',
      country: '',
      date_enrolled: '2011-01-04',
      date_of_birth: '2020-04-10',
      date_renewed: null,
      email: 'lbchouhan@gmail.com',
      expiry_date: '2022-03-31',
      fax: '',
      firstname: 'Mr. Lal Bahadur',
      gender: 'M',
      incorrect_address: false,
      initials: '',
      lang: 'default',
      last_seen: null,
      library_id: 'TUCL',
      login_attempts: 0,
      mobile: '9849295952',
      opac_notes: 'Welcome TUCL OPAC. Please change your OPAC Password',
      other_name: '',
      overdrive_auth_token: null,
      patron_card_lost: false,
      patron_id: 71,
      phone: '',
      postal_code: '',
      privacy: 1,
      privacy_guarantor_checkouts: 0,
      privacy_guarantor_fines: false,
      relationship_type: null,
      restricted: false,
      secondary_email: '',
      secondary_phone: '',
      sms_number: null,
      sms_provider_id: null,
      staff_notes: '',
      state: '',
      statistics_1: 'Library Officer',
      statistics_2: '',
      street_number: '',
      street_type: null,
      surname: 'Chouhan',
      title: 'Mr',
      updated_on: '2021-12-09T10:43:40+05:45',
      userid: 'lalbahadur.chouhan',
    },
    {
      address: 'Tulachhen Tole, Bhaktapur - 8',
      address2: '',
      altaddress_address: '',
      altaddress_address2: '',
      altaddress_city: '',
      altaddress_country: '',
      altaddress_email: '',
      altaddress_notes: '',
      altaddress_phone: '',
      altaddress_postal_code: '',
      altaddress_state: '',
      altaddress_street_number: null,
      altaddress_street_type: null,
      altcontact_address: '',
      altcontact_address2: '',
      altcontact_city: '',
      altcontact_country: '',
      altcontact_firstname: '',
      altcontact_phone: '',
      altcontact_postal_code: '',
      altcontact_state: '',
      altcontact_surname: '',
      anonymized: false,
      autorenew_checkouts: false,
      cardnumber: '00015',
      category_id: 'TCLSG1',
      check_previous_checkout: 'inherit',
      city: '',
      country: '',
      date_enrolled: '2011-01-23',
      date_of_birth: '2017-02-07',
      date_renewed: null,
      email: 'kamalkayastha@gmail.com',
      expiry_date: '2020-03-21',
      fax: '',
      firstname: 'Mr. Kamal Bdr.',
      gender: 'M',
      incorrect_address: false,
      initials: '',
      lang: 'default',
      last_seen: null,
      library_id: 'TUCL',
      login_attempts: 0,
      mobile: '',
      opac_notes: '',
      other_name: '',
      overdrive_auth_token: null,
      patron_card_lost: false,
      patron_id: 72,
      phone: '9841211799',
      postal_code: '',
      privacy: 1,
      privacy_guarantor_checkouts: 0,
      privacy_guarantor_fines: false,
      relationship_type: null,
      restricted: false,
      secondary_email: 'kamal.kayastha@tucl.org.np',
      secondary_phone: ' 6612444',
      sms_number: null,
      sms_provider_id: null,
      staff_notes: '',
      state: '',
      statistics_1: '',
      statistics_2: '',
      street_number: '',
      street_type: null,
      surname: 'Kayastha',
      title: 'Mr',
      updated_on: '2021-12-09T10:43:40+05:45',
      userid: 'kamal.kayastha',
    },
    {
      address: 'Lokanthali-16, Bhaktapur',
      address2: '',
      altaddress_address: '',
      altaddress_address2: null,
      altaddress_city: '',
      altaddress_country: null,
      altaddress_email: '',
      altaddress_notes: '',
      altaddress_phone: '',
      altaddress_postal_code: '',
      altaddress_state: null,
      altaddress_street_number: null,
      altaddress_street_type: null,
      altcontact_address: '',
      altcontact_address2: '',
      altcontact_city: '',
      altcontact_country: null,
      altcontact_firstname: '',
      altcontact_phone: '',
      altcontact_postal_code: '',
      altcontact_state: null,
      altcontact_surname: '',
      anonymized: false,
      autorenew_checkouts: false,
      cardnumber: '00016',
      category_id: 'TCLSG1',
      check_previous_checkout: 'inherit',
      city: '',
      country: null,
      date_enrolled: '2010-10-20',
      date_of_birth: '2020-01-20',
      date_renewed: null,
      email: 'kalpana.karki@tucl.org.np',
      expiry_date: '2016-12-31',
      fax: '',
      firstname: 'Kalpana',
      gender: 'F',
      incorrect_address: false,
      initials: '',
      lang: 'default',
      last_seen: null,
      library_id: 'TUCL',
      login_attempts: 0,
      mobile: '',
      opac_notes: '',
      other_name: '',
      overdrive_auth_token: null,
      patron_card_lost: false,
      patron_id: 73,
      phone: '9813516670',
      postal_code: '',
      privacy: 1,
      privacy_guarantor_checkouts: 0,
      privacy_guarantor_fines: false,
      relationship_type: null,
      restricted: false,
      secondary_email: '',
      secondary_phone: '4231446',
      sms_number: null,
      sms_provider_id: null,
      staff_notes: '',
      state: null,
      statistics_1: '',
      statistics_2: '',
      street_number: '',
      street_type: null,
      surname: 'Karki',
      title: 'Mrs',
      updated_on: '2021-12-09T10:43:40+05:45',
      userid: 'kalpana.karki',
    },
    {
      address: 'Buddhanagar, Kathmandu',
      address2: 'Naya Baneshwor',
      altaddress_address: '',
      altaddress_address2: null,
      altaddress_city: '',
      altaddress_country: null,
      altaddress_email: '',
      altaddress_notes: '',
      altaddress_phone: '',
      altaddress_postal_code: '',
      altaddress_state: null,
      altaddress_street_number: null,
      altaddress_street_type: null,
      altcontact_address: '',
      altcontact_address2: '',
      altcontact_city: '',
      altcontact_country: null,
      altcontact_firstname: '',
      altcontact_phone: '',
      altcontact_postal_code: '',
      altcontact_state: null,
      altcontact_surname: '',
      anonymized: false,
      autorenew_checkouts: false,
      cardnumber: '00055',
      category_id: 'TCLSG2',
      check_previous_checkout: 'inherit',
      city: '',
      country: '',
      date_enrolled: '2010-10-20',
      date_of_birth: '2018-11-27',
      date_renewed: null,
      email: 'himalrupa.ghimire@tucl.org.np',
      expiry_date: '2016-12-30',
      fax: '',
      firstname: 'Himalrupa',
      gender: 'F',
      incorrect_address: false,
      initials: '',
      lang: 'default',
      last_seen: null,
      library_id: 'TUCL',
      login_attempts: 0,
      mobile: '',
      opac_notes: '',
      other_name: '',
      overdrive_auth_token: null,
      patron_card_lost: false,
      patron_id: 75,
      phone: '9849499251',
      postal_code: '',
      privacy: 1,
      privacy_guarantor_checkouts: 0,
      privacy_guarantor_fines: false,
      relationship_type: null,
      restricted: false,
      secondary_email: '',
      secondary_phone: '',
      sms_number: null,
      sms_provider_id: null,
      staff_notes: '',
      state: '',
      statistics_1: '',
      statistics_2: '',
      street_number: '',
      street_type: null,
      surname: 'Ghimire',
      title: 'Mrs',
      updated_on: '2021-12-09T10:43:40+05:45',
      userid: 'himalrupa.ghimire',
    },
    {
      address: 'Mahadevsthan, Kathmandu',
      address2: '',
      altaddress_address: '',
      altaddress_address2: null,
      altaddress_city: '',
      altaddress_country: null,
      altaddress_email: '',
      altaddress_notes: '',
      altaddress_phone: '',
      altaddress_postal_code: '',
      altaddress_state: null,
      altaddress_street_number: null,
      altaddress_street_type: null,
      altcontact_address: '',
      altcontact_address2: '',
      altcontact_city: '',
      altcontact_country: null,
      altcontact_firstname: '',
      altcontact_phone: '',
      altcontact_postal_code: '',
      altcontact_state: null,
      altcontact_surname: '',
      anonymized: false,
      autorenew_checkouts: false,
      cardnumber: '00019',
      category_id: 'TCLSG2',
      check_previous_checkout: 'inherit',
      city: '',
      country: null,
      date_enrolled: '2010-10-20',
      date_of_birth: null,
      date_renewed: null,
      email: '',
      expiry_date: '2011-10-20',
      fax: '',
      firstname: 'Mr. Gokul Kumar',
      gender: 'M',
      incorrect_address: false,
      initials: '',
      lang: 'default',
      last_seen: null,
      library_id: 'TUCL',
      login_attempts: 0,
      mobile: '',
      opac_notes: '',
      other_name: '',
      overdrive_auth_token: null,
      patron_card_lost: false,
      patron_id: 76,
      phone: '9841559246',
      postal_code: '',
      privacy: 1,
      privacy_guarantor_checkouts: 0,
      privacy_guarantor_fines: false,
      relationship_type: null,
      restricted: false,
      secondary_email: 'gokulkumar.thapa@tucl.org.np',
      secondary_phone: '',
      sms_number: null,
      sms_provider_id: null,
      staff_notes: '',
      state: null,
      statistics_1: '',
      statistics_2: '',
      street_number: '',
      street_type: null,
      surname: 'Thapa',
      title: 'Mr',
      updated_on: '2021-12-09T10:43:40+05:45',
      userid: 'gokulkumar.thapa',
    },
    {
      address: 'Balkhu, Kathmandu',
      address2: '',
      altaddress_address: '',
      altaddress_address2: null,
      altaddress_city: '',
      altaddress_country: null,
      altaddress_email: '',
      altaddress_notes: '',
      altaddress_phone: '',
      altaddress_postal_code: '',
      altaddress_state: null,
      altaddress_street_number: null,
      altaddress_street_type: null,
      altcontact_address: '',
      altcontact_address2: '',
      altcontact_city: '',
      altcontact_country: null,
      altcontact_firstname: '',
      altcontact_phone: '',
      altcontact_postal_code: '',
      altcontact_state: null,
      altcontact_surname: '',
      anonymized: false,
      autorenew_checkouts: false,
      cardnumber: '00022',
      category_id: 'TCLSG2',
      check_previous_checkout: 'inherit',
      city: '',
      country: null,
      date_enrolled: '2017-12-31',
      date_of_birth: '2030-04-13',
      date_renewed: null,
      email: 'rita.kharel@tucl.org.np',
      expiry_date: '2017-12-31',
      fax: '',
      firstname: 'Rita',
      gender: 'F',
      incorrect_address: false,
      initials: '',
      lang: 'default',
      last_seen: null,
      library_id: 'TUCL',
      login_attempts: 0,
      mobile: '',
      opac_notes: 'Please change your OPAC password',
      other_name: '',
      overdrive_auth_token: null,
      patron_card_lost: false,
      patron_id: 79,
      phone: '',
      postal_code: '',
      privacy: 1,
      privacy_guarantor_checkouts: 0,
      privacy_guarantor_fines: false,
      relationship_type: null,
      restricted: false,
      secondary_email: '',
      secondary_phone: '',
      sms_number: null,
      sms_provider_id: null,
      staff_notes: '',
      state: null,
      statistics_1: '',
      statistics_2: '',
      street_number: '',
      street_type: null,
      surname: 'Kharel',
      title: 'Mrs',
      updated_on: '2021-12-09T10:43:40+05:45',
      userid: 'rita.kharel',
    },
    {
      address: 'Kirtipur, Kathmandu',
      address2: 'Ward No.11, Panga',
      altaddress_address: '',
      altaddress_address2: null,
      altaddress_city: '',
      altaddress_country: null,
      altaddress_email: '',
      altaddress_notes: '',
      altaddress_phone: '',
      altaddress_postal_code: '',
      altaddress_state: null,
      altaddress_street_number: null,
      altaddress_street_type: null,
      altcontact_address: '',
      altcontact_address2: '',
      altcontact_city: '',
      altcontact_country: null,
      altcontact_firstname: '',
      altcontact_phone: '',
      altcontact_postal_code: '',
      altcontact_state: null,
      altcontact_surname: '',
      anonymized: false,
      autorenew_checkouts: false,
      cardnumber: '00024',
      category_id: 'TCLSG2',
      check_previous_checkout: 'inherit',
      city: 'Kathmandu',
      country: null,
      date_enrolled: '2010-12-17',
      date_of_birth: '2011-07-15',
      date_renewed: null,
      email: 'madansingh.maharjan@tucl.org.np',
      expiry_date: '2015-12-16',
      fax: '',
      firstname: 'Madan Singh',
      gender: 'M',
      incorrect_address: false,
      initials: '',
      lang: 'default',
      last_seen: null,
      library_id: 'TUCL',
      login_attempts: 0,
      mobile: '',
      opac_notes: 'Please change your OPAC password',
      other_name: '',
      overdrive_auth_token: null,
      patron_card_lost: false,
      patron_id: 81,
      phone: '9841432433',
      postal_code: '',
      privacy: 1,
      privacy_guarantor_checkouts: 0,
      privacy_guarantor_fines: false,
      relationship_type: null,
      restricted: false,
      secondary_email: '',
      secondary_phone: '4332618',
      sms_number: null,
      sms_provider_id: null,
      staff_notes: '',
      state: null,
      statistics_1: '',
      statistics_2: '',
      street_number: '',
      street_type: null,
      surname: 'Maharjan',
      title: 'Mr',
      updated_on: '2021-12-09T10:43:40+05:45',
      userid: 'madansingh.maharjan',
    },
    {
      address: 'Dahachowk-2 Kathmandu',
      address2: '',
      altaddress_address: '',
      altaddress_address2: '',
      altaddress_city: '',
      altaddress_country: '',
      altaddress_email: '',
      altaddress_notes: '',
      altaddress_phone: '',
      altaddress_postal_code: '',
      altaddress_state: '',
      altaddress_street_number: null,
      altaddress_street_type: null,
      altcontact_address: '',
      altcontact_address2: '',
      altcontact_city: '',
      altcontact_country: '',
      altcontact_firstname: '',
      altcontact_phone: '',
      altcontact_postal_code: '',
      altcontact_state: '',
      altcontact_surname: '',
      anonymized: false,
      autorenew_checkouts: false,
      cardnumber: '00025',
      category_id: 'TCLSG2',
      check_previous_checkout: 'inherit',
      city: '',
      country: '',
      date_enrolled: '2010-10-20',
      date_of_birth: '2017-01-23',
      date_renewed: null,
      email: 'hsgiri@hotmail.com',
      expiry_date: null,
      fax: '',
      firstname: 'Harisharan',
      gender: 'M',
      incorrect_address: false,
      initials: '',
      lang: 'default',
      last_seen: null,
      library_id: 'TUCL',
      login_attempts: 0,
      mobile: '',
      opac_notes: 'Please change your opac password.',
      other_name: '',
      overdrive_auth_token: null,
      patron_card_lost: false,
      patron_id: 82,
      phone: '9841778623',
      postal_code: '',
      privacy: 1,
      privacy_guarantor_checkouts: 0,
      privacy_guarantor_fines: false,
      relationship_type: null,
      restricted: false,
      secondary_email: 'harisharan.giri@tucl.org.np',
      secondary_phone: '4314978',
      sms_number: null,
      sms_provider_id: null,
      staff_notes: '',
      state: '',
      statistics_1: '',
      statistics_2: '',
      street_number: '',
      street_type: null,
      surname: 'Giri',
      title: 'Mr',
      updated_on: '2021-12-09T10:43:40+05:45',
      userid: 'harisharan.giri',
    },
    {
      address: 'Siddhipur , Lalitpur',
      address2: '',
      altaddress_address: '',
      altaddress_address2: null,
      altaddress_city: '',
      altaddress_country: null,
      altaddress_email: '',
      altaddress_notes: '',
      altaddress_phone: '',
      altaddress_postal_code: '',
      altaddress_state: null,
      altaddress_street_number: null,
      altaddress_street_type: null,
      altcontact_address: '',
      altcontact_address2: '',
      altcontact_city: '',
      altcontact_country: null,
      altcontact_firstname: '',
      altcontact_phone: '',
      altcontact_postal_code: '',
      altcontact_state: null,
      altcontact_surname: '',
      anonymized: false,
      autorenew_checkouts: false,
      cardnumber: '00026',
      category_id: 'TCLSG1',
      check_previous_checkout: 'inherit',
      city: '',
      country: null,
      date_enrolled: '2010-12-26',
      date_of_birth: '2019-02-01',
      date_renewed: null,
      email: 'laxmibahadur.nemkul@tucl.org.np',
      expiry_date: '2015-12-26',
      fax: '',
      firstname: 'Mr. Laxmi Bahadur',
      gender: 'M',
      incorrect_address: false,
      initials: '',
      lang: 'default',
      last_seen: null,
      library_id: 'TUCL',
      login_attempts: 0,
      mobile: '',
      opac_notes: '',
      other_name: '',
      overdrive_auth_token: null,
      patron_card_lost: false,
      patron_id: 83,
      phone: '5581152',
      postal_code: '',
      privacy: 1,
      privacy_guarantor_checkouts: 0,
      privacy_guarantor_fines: false,
      relationship_type: null,
      restricted: false,
      secondary_email: '',
      secondary_phone: '',
      sms_number: null,
      sms_provider_id: null,
      staff_notes: '',
      state: null,
      statistics_1: '',
      statistics_2: '',
      street_number: '',
      street_type: null,
      surname: 'Nemkul',
      title: 'Mr',
      updated_on: '2021-12-09T10:43:40+05:45',
      userid: 'laxmibahadur.nemkul',
    },
    {
      address: 'Kapan-3, Kathmandu',
      address2: 'Kapan-3 Kathmandu',
      altaddress_address: '',
      altaddress_address2: '',
      altaddress_city: '',
      altaddress_country: '',
      altaddress_email: '',
      altaddress_notes: '',
      altaddress_phone: '',
      altaddress_postal_code: '',
      altaddress_state: '',
      altaddress_street_number: null,
      altaddress_street_type: null,
      altcontact_address: '',
      altcontact_address2: '',
      altcontact_city: '',
      altcontact_country: '',
      altcontact_firstname: '',
      altcontact_phone: '',
      altcontact_postal_code: '',
      altcontact_state: '',
      altcontact_surname: '',
      anonymized: false,
      autorenew_checkouts: false,
      cardnumber: '00027',
      category_id: 'TCLSG1',
      check_previous_checkout: 'inherit',
      city: '',
      country: '',
      date_enrolled: '2013-12-24',
      date_of_birth: null,
      date_renewed: null,
      email: 'mitharam.dhakal@tucl.org.np',
      expiry_date: '2020-12-24',
      fax: '',
      firstname: 'Mr. Mitha Ram',
      gender: 'M',
      incorrect_address: false,
      initials: '',
      lang: 'default',
      last_seen: null,
      library_id: 'TUCL',
      login_attempts: 0,
      mobile: '',
      opac_notes: 'Please change your OPAC password.',
      other_name: '',
      overdrive_auth_token: null,
      patron_card_lost: false,
      patron_id: 84,
      phone: '9841931126',
      postal_code: '',
      privacy: 1,
      privacy_guarantor_checkouts: 0,
      privacy_guarantor_fines: false,
      relationship_type: null,
      restricted: false,
      secondary_email: '',
      secondary_phone: '',
      sms_number: null,
      sms_provider_id: null,
      staff_notes: '',
      state: '',
      statistics_1: '',
      statistics_2: '',
      street_number: '',
      street_type: null,
      surname: 'Dhakal',
      title: 'Mr',
      updated_on: '2021-12-09T10:43:40+05:45',
      userid: 'mitharam.dhakal',
    },
    {
      address: 'Kirtipur, Kathmandu',
      address2: '',
      altaddress_address: '',
      altaddress_address2: '',
      altaddress_city: '',
      altaddress_country: '',
      altaddress_email: '',
      altaddress_notes: '',
      altaddress_phone: '',
      altaddress_postal_code: '',
      altaddress_state: '',
      altaddress_street_number: null,
      altaddress_street_type: null,
      altcontact_address: '',
      altcontact_address2: '',
      altcontact_city: '',
      altcontact_country: '',
      altcontact_firstname: '',
      altcontact_phone: '',
      altcontact_postal_code: '',
      altcontact_state: '',
      altcontact_surname: '',
      anonymized: false,
      autorenew_checkouts: false,
      cardnumber: '00028',
      category_id: 'TCLSG2',
      check_previous_checkout: 'inherit',
      city: '',
      country: '',
      date_enrolled: '2010-12-28',
      date_of_birth: '2036-10-09',
      date_renewed: null,
      email: 'premshova.dangol@tucl.org.np',
      expiry_date: '2021-12-31',
      fax: '',
      firstname: 'Premshova',
      gender: 'F',
      incorrect_address: false,
      initials: '',
      lang: 'default',
      last_seen: null,
      library_id: 'TUCL',
      login_attempts: 0,
      mobile: '',
      opac_notes: 'Please change your OPAC password',
      other_name: '',
      overdrive_auth_token: null,
      patron_card_lost: false,
      patron_id: 85,
      phone: '9849427142',
      postal_code: '',
      privacy: 1,
      privacy_guarantor_checkouts: 0,
      privacy_guarantor_fines: false,
      relationship_type: null,
      restricted: false,
      secondary_email: '',
      secondary_phone: '',
      sms_number: null,
      sms_provider_id: null,
      staff_notes: '',
      state: '',
      statistics_1: '',
      statistics_2: '',
      street_number: '',
      street_type: null,
      surname: 'Dangol',
      title: 'Mrs',
      updated_on: '2021-12-09T10:43:40+05:45',
      userid: 'premshova.dangol',
    },
    {
      address: 'Mahankal, Kathmandu',
      address2: '',
      altaddress_address: '',
      altaddress_address2: '',
      altaddress_city: '',
      altaddress_country: '',
      altaddress_email: '',
      altaddress_notes: '',
      altaddress_phone: '',
      altaddress_postal_code: '',
      altaddress_state: '',
      altaddress_street_number: null,
      altaddress_street_type: null,
      altcontact_address: '',
      altcontact_address2: '',
      altcontact_city: '',
      altcontact_country: '',
      altcontact_firstname: '',
      altcontact_phone: '',
      altcontact_postal_code: '',
      altcontact_state: '',
      altcontact_surname: '',
      anonymized: false,
      autorenew_checkouts: false,
      cardnumber: '00029',
      category_id: 'TCLSG2',
      check_previous_checkout: 'inherit',
      city: '',
      country: '',
      date_enrolled: '2010-12-28',
      date_of_birth: '2028-11-26',
      date_renewed: null,
      email: 'laxmi.shrestha@tucl.org.np',
      expiry_date: '2020-12-30',
      fax: '',
      firstname: 'Laxmi',
      gender: 'F',
      incorrect_address: false,
      initials: '',
      lang: 'default',
      last_seen: null,
      library_id: 'TUCL',
      login_attempts: 0,
      mobile: '',
      opac_notes: 'Please change your OPAC password',
      other_name: '',
      overdrive_auth_token: null,
      patron_card_lost: false,
      patron_id: 86,
      phone: '9841396663',
      postal_code: '',
      privacy: 1,
      privacy_guarantor_checkouts: 0,
      privacy_guarantor_fines: false,
      relationship_type: null,
      restricted: false,
      secondary_email: '',
      secondary_phone: '',
      sms_number: null,
      sms_provider_id: null,
      staff_notes: '',
      state: '',
      statistics_1: '',
      statistics_2: '',
      street_number: '',
      street_type: null,
      surname: 'Shrestha',
      title: 'Ms',
      updated_on: '2021-12-09T10:43:40+05:45',
      userid: 'laxmi.shrestha',
    },
    {
      address: 'Jaishi Dewal, Kathmandu',
      address2: '',
      altaddress_address: '',
      altaddress_address2: null,
      altaddress_city: '',
      altaddress_country: null,
      altaddress_email: '',
      altaddress_notes: '',
      altaddress_phone: '',
      altaddress_postal_code: '',
      altaddress_state: null,
      altaddress_street_number: null,
      altaddress_street_type: null,
      altcontact_address: '',
      altcontact_address2: '',
      altcontact_city: '',
      altcontact_country: null,
      altcontact_firstname: '',
      altcontact_phone: '',
      altcontact_postal_code: '',
      altcontact_state: null,
      altcontact_surname: '',
      anonymized: false,
      autorenew_checkouts: false,
      cardnumber: '00030',
      category_id: 'TCLSG2',
      check_previous_checkout: 'inherit',
      city: '',
      country: '',
      date_enrolled: '2011-01-13',
      date_of_birth: null,
      date_renewed: null,
      email: 'harigopal.shrestha@tucl.org.np',
      expiry_date: '2015-01-13',
      fax: '',
      firstname: ' Harigopal',
      gender: 'M',
      incorrect_address: false,
      initials: '',
      lang: 'default',
      last_seen: null,
      library_id: 'TUCL',
      login_attempts: 0,
      mobile: '',
      opac_notes: '',
      other_name: '',
      overdrive_auth_token: null,
      patron_card_lost: false,
      patron_id: 87,
      phone: '9841438976',
      postal_code: '',
      privacy: 1,
      privacy_guarantor_checkouts: 0,
      privacy_guarantor_fines: false,
      relationship_type: null,
      restricted: false,
      secondary_email: '',
      secondary_phone: '',
      sms_number: null,
      sms_provider_id: null,
      staff_notes: '',
      state: '',
      statistics_1: '',
      statistics_2: '',
      street_number: '',
      street_type: null,
      surname: 'Shrestha',
      title: 'Mr',
      updated_on: '2021-12-09T10:43:40+05:45',
      userid: 'harigopal.shrestha',
    },
  ];

  @ViewChild('select') select: MatSelect;

  allSelected = false;

  // Expansion pannel and forms details
  cardsForm: FormGroup;
  panelOpenState: boolean = false;
  signatureFile?: FileList;
  selectedSignature: string[] = [];
  signaturePreview: string[] = [];
  stampFile?: FileList;
  selectedStamp: string[] = [];
  stampPreview: string[] = [];

  signatureImagePath: string[] = ['../../../assets/sign.png'];
  stampImagePath: string[] = ['../../../assets/stamp.png'];
  universityName: string = 'Tribhuwan University';
  department: string = 'Central Library';
  address: string = 'Kirtipur, Kathmandu';
  email: string = 'tucl@tucl.org.np';
  url: string = 'www.tucl.org.np';
  phone: string = '+977-1-4331317,43331318';

  generatedImage: string[] = [];

  constructor(private fb: FormBuilder) {}

  ngOnInit() {
    this.initForm();
  }

  // Form init using form builder
  private initForm() {
    this.cardsForm = this.fb.group({
      universityName: 'Tribhuwan University',
      department: 'Central Library',
      address: 'Kirtipur, Kathmandu',
      email: 'tucl@tucl.org.np',
      url: 'www.tucl.org.np',
      phoneNo: '+977-1-4331317,43331318',
    });
  }

  selectSignatureFiles(event: any): void {
    this.signatureImagePath = [];
    this.signatureFile = event.target.files;
    if (this.signatureFile && this.signatureFile[0]) {
      const numberOfFiles = this.signatureFile.length;
      for (let i = 0; i < numberOfFiles; i++) {
        const reader = new FileReader();
        reader.onload = (e: any) => {
          this.signaturePreview.push(e.target.result);
        };
        reader.readAsDataURL(this.signatureFile[i]);
        this.selectedSignature.push(this.signatureFile[i].name);
      }
    }
  }

  selectStampFiles(event: any): void {
    this.stampImagePath = [];
    this.stampFile = event.target.files;
    if (this.stampFile && this.stampFile[0]) {
      const numberOfFiles = this.stampFile.length;
      for (let i = 0; i < numberOfFiles; i++) {
        const reader = new FileReader();
        reader.onload = (e: any) => {
          this.stampPreview.push(e.target.result);
        };
        reader.readAsDataURL(this.stampFile[i]);
        this.selectedStamp.push(this.stampFile[i].name);
      }
    }
  }

  uploadFiles() {
    this.signatureImagePath = this.signaturePreview;
    this.stampImagePath = this.stampPreview;
  }

  save() {
    this.universityName = this.cardsForm.value.universityName;
    this.department = this.cardsForm.value.department;
    this.address = this.cardsForm.value.address;
    (this.email = this.cardsForm.value.email),
      (this.url = this.cardsForm.value.url);
    this.phone = this.cardsForm.value.phoneNo;
    this.uploadFiles();
  }

  async individualDownload() {
    // let d = document.querySelectorAll('[id=myCard]');
    // d.forEach(async (item) => {
    //   // let el =

    //   console.log(item, 'canvas')
    //   const canvas = await html2canvas(
    //     document.getElementById(item.id) as HTMLImageElement
    //   );

    //       canvas.style.display = "block";
    //   document.body.appendChild(canvas);
    //   const image = canvas
    //     .toDataURL("image/png")
    //     .replace("image/png", "image/octet-stream");
    //     console.log(image, 'imagesss')

    // })
    // for(let i=1;i<=this.userLists.length;i++) {

    // }

    this.userLists.forEach(async (item, cId) => {
      // let el = document.getElementById(item.email) as HTMLImageElement;
      const canvas = await html2canvas(
        document.getElementById(item.email) as HTMLImageElement
      );
      canvas.style.display = 'block';
      document.body.appendChild(canvas);
      const image = canvas
        .toDataURL('image/png')
        .replace('image/png', 'image/octet-stream');
      let img = canvas
        .toDataURL('image/png')
        .replace(/^data:image\/(png|jpg);base64,/, '');
      this.generatedImage.push(img);

      var zip = new JSZip();
      zip.folder('cards');
      for (let i = 0; i <= this.generatedImage.length; i++) {
        zip.file(i + 'card.png', this.generatedImage[i], { base64: true });
      }

      if (this.generatedImage.length >= 4) {
        zip.generateAsync({ type: 'blob' }).then(function (content: any) {
          FileSaver.saveAs(content, 'cards.zip');
        });
      }

      // const a = document.createElement("a");
      // a.style.display = "none";
      // a.setAttribute("download", 'card' + `.png`);
      // a.setAttribute("href", image);
      // a.click();
    });

    // let el = document.getElementById("myCard") as HTMLImageElement;
    // const canvas = await html2canvas(el);

    //   canvas.style.display = "block";
    //   document.body.appendChild(canvas);
    //   const image = canvas
    //     .toDataURL("image/png")
    //     .replace("image/png", "image/octet-stream");
    //     console.log(image, 'imagesss')

    //   const a = document.createElement("a");
    //   a.style.display = "none";
    //   a.setAttribute("download", data + `.png`);
    //   a.setAttribute("href", image);
    //   a.click();
  }

  toggleAllSelection() {
    if (this.allSelected) {
      this.select.options.forEach((item: MatOption) => item.select());
    } else {
      this.select.options.forEach((item: MatOption) => item.deselect());
    }
  }

  optionClick() {
    let newStatus = true;
    this.select.options.forEach((item: MatOption) => {
      if (!item.selected) {
        newStatus = false;
      }
    });
    this.allSelected = newStatus;
  }

  generateCard(data: any) {
    console.log(data);
  }

  async printCard(data: any) {
    const canvas = await html2canvas(
      document.getElementById('card') as HTMLImageElement
    );
    canvas.style.display = 'block';
    document.body.appendChild(canvas);
    const image = canvas
      .toDataURL('image/png')
      .replace('image/png', 'image/octet-stream');

    const a = document.createElement('a');
    a.style.display = 'none';
    a.setAttribute('download', data.firstname + `.png`);
    a.setAttribute('href', image);
    a.click();
  }

  upload(): void {
    this.signatureImagePath = this.previews;
  }

  downloadZip() {
    // const zip = new JSZip();
    // zip.file('hello.txt', 'Hello[p my)6cxsw2q');
    // zip.file('hello1.txt', 'Hello World\n');
    // zip.generateAsync({ type: 'blob' }).then(function (content:any) {
    //   zip.loadAsync(content).then(function (zip:any) {
    //     console.log(zip);
    //   });
    // });
  }
}
